name: mp_mk
description: Flutter Media Player using media_kit

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # media_kit: ^1.1.12
  # media_kit_video: ^1.3.0
  # media_kit_libs_video: ^1.0.6
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
